### PR TITLE
Adding osv detector

### PR DESCRIPTION
**Pull request by Dimithri**
JIRA ticket: https://ackama.atlassian.net/browse/N2-36

This PR is to add auditing tool for the repository. Tool we have chosen is https://github.com/G-Rath/osv-detector, as per the suggestion by @G-Rath.

### CODE REVIEW

**Review by G-Rath — APPROVED** [review]
Looks good to me! I'd recommend ignoring the existing vulnerabilities by creating an `.osv-detector.yaml` in the root of the repository, and then doing followup PRs addressing each one

**Review by jonholdsworth — APPROVED** [review]
I'll leave it to you to implement Gareth's recomendations. :)

**Review by joshmcarthur — APPROVED** [review]
@G-Rath if we're going to start implementing this check across all Ackama projects, it might be a good idea to have a fork of the action ourselves to show that it's "ours"?

**Comment by G-Rath** [comment]
@joshmcarthur this might be worth talking about on Slack - my thinking was it made sense to have it in my personal because that's where `osv-detector` is, and also I'm in chats with Google about them having it as their official tool (so it'd live in the OSV org) so it might  be moot anyway...

But I personally am not fussed so maybe there's a stronger advantage in having it in the ackama org than I realise 🤷

**Pull request merged**
