### PR TITLE
re-constrain certifi >= 2024.07.04 for GHSA-248v-346w-9cwc

### PR DESCRIPTION
**Pull request by jonholdsworth**
Addresses:

[GHSA-248v-346w-9cwc - Certifi removes GLOBALTRUST root certificate](https://github.com/advisories/GHSA-248v-346w-9cwc)

## Changes

- re-constrain `certifi` >= `2024.07.04` for `GHSA-248v-346w-9cwc`

### CODE REVIEW

**Comment by jonholdsworth** [comment]
Holding off merging this until Poetry conversion tasks complete.

**Comment by G-Rath** [comment]
fwiw Dependabot has already opened #176 for this 😅

**Comment by jonholdsworth** [comment]
> fwiw Dependabot has already opened #176 for this 😅

Ugh, didn't see that it had already changed the version in `pyproject.toml`.
I'll dump this PR and go with the Dependabot one after all. 😆

**Comment by jonholdsworth** [comment]
Closing in favour of #176

**Pull request closed without merging**
