### PR TITLE
N2-40, 41, 42 , 86: Implement a comprehensive README to achieve the objectives of Codecare setup tasks

### PR DESCRIPTION
**Pull request by joshmcarthur**
N2-40: Document the branching conventions & deployment process

* I've added branch documentation to the README. Our internal README template links out to our wiki, so I've inlined guidance from the wiki page so that this documentation is standalone.

N2-41: Ensure that the README & other docs are up to date, and remove any outdated content that might cause confusion

* I've filled in all relevant sections of the README, reworded for a Python project instead of Rails
* I've removed the FinSL documentation. This is linked to in the README, but leaving it in our fork seemed like it could cause confusion.

N2-42: Document any particular pain points or misc. things about the app that might be good to have written up

* Known errors or warnings that don't cause bugs, but can still look scary (i.e X tends to trigger a Sentry event when you deploy)

> * That dependency that always seems to give you trouble when you update it,
> * That command that never seems to work right on this particular app,
> * That test that always seems to fail just when you've forgotten about it,
> * Any actions or requests that the client may expect to be done (i.e we give Y a work report every month, the Z app has us add a new interest rate every now and again, etc)

* I've added a section to the README with gotchas and known issues and filled it in with a bunch that occurred to me. I'd appreciate if @jonholdsworth or @Dimithri have any suggestions that we add to the README _now_ while we remember what they are, so that Codecare doesn't find out the hard way.

N2-86: Establish boundaries of support in terms of merging features, which parts we actively maintain etc

> We’re going to continue having requests for features from the global signbank. We need to document which parts of signbank we have worked on, which come from the global signbank and which come from the Finnish signbank project so that we’re clear which features we have ownership over (vs which we should be looking for bugfixes upstream)

* I've documented key differences between NZSL Signbank and FinSL
* I've linked to an always-up-to-date comparison diff on Github between our fork and FinSL

### CODE REVIEW

**Comment by joshmcarthur** [comment]
@G-Rath just tagged you because I thought you might like to scan the README and see if there's anything that I should include that isn't there, or anything I've included that could be misleading or incorrect.

**Comment by joshmcarthur** [comment]
I suggest [viewing the README file directly](https://github.com/ODNZSL/NZSL-signbank/blob/c22b3a1165c1d90123b4ccdbb61cd87b024b4f11/README.md) rather than trying to parse the diff

**Review by jonholdsworth — APPROVED** [review]
All looks pretty good.
The only 'Gotchas' aspect I can think of is the media migration, ensuring the environment is honoured properly (and that eg. the migration does not attempt to copy all the S3 assets somewhere).

**Review by Dimithri — APPROVED** [review]
Looks good! :smile:

**Pull request merged**
