### PR TITLE
Task/n2 28 configure language settings

### PR DESCRIPTION
**Pull request by jonholdsworth**
postgres port 5432 exposed as port 5432 on localhost
'fi' removed from LANGUAGES in settings.
'fi' LOCALE removed.
Database/Models remigrated, initial data dumped back to JSON.
Static content pages edited and some removed in database to change Finnish references to NZ.

### CODE REVIEW

**Review by joshmcarthur — CHANGES_REQUESTED** [review]
👏  nice start! Just looking at the flatpages fixture, it looks like it has contenttypes and other types of models in there when it should just be flatpages. Is there a chance you ran `dumpdata` without specifying the app name to dump? That file should really only have fixtures for flatpages, not for all apps

**Comment by jonholdsworth** [comment]
Oh oh, yes that's exactly what happened! My bad.

I'll re-do it.

**Comment by jonholdsworth** [comment]
Ok fixed, JSON only contains flatpages. Site tested, works as before.

**Review by joshmcarthur — APPROVED** [review]
Nice one!

**Pull request merged**
